/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InputTools: typeof import('./src/components/input-tools/index.vue')['default']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
  }
}
